### ISSUE TITLE
Incorrect result set... am I missing something?

### ISSUE THREAD

**Issue by raghubetina** [vlado/activerecord-cte#9]
Hi there,

I was testing out the library with Ruby 3.0.1 and Rails 6.1.4, and seem to be getting the wrong result when trying out the example query from the documentation. [Here's the toy app I was testing with](https://github.com/raghubetina/cte-test#testing-activerecordcte); am I missing something?

Thank you!

**Comment by nflorentin** [comment]
Same here, I have 5 products:
- id: 1, position: 0
- id: 2, position: 1
- id: 3, position: 2
- id: 4, position: 3
- id: 5, position: 4

The following code:
```ruby
Product.with(products_with_position_greater_than_3: Product.where("position > 3"))
```
is producing this sql:
```SQL
 WITH "products_with_position_greater_than_3" AS (SELECT "products".* FROM "products" WHERE (position > 3)) SELECT "products".* FROM "products"
```

But the result set contains the 5 products.
```ruby
Product.with(products_with_position_greater_than_3: Product.where("products.position > 3")).count # => returns 5 instead of 1
```

**Comment by raghubetina** [comment]
@nflorentin Ahh, thank you.

@vlado Perhaps a slight re-ordering of the documentation might save you repeated questions from dummies like me in the future.

**Comment by vlado** [comment]
> @vlado Perhaps a slight re-ordering of the documentation might save you repeated questions from dummies like me in the future.

Yes, will see what I can do with the docs ;)

**Comment by vlado** [comment]
Readme updated https://github.com/vlado/activerecord-cte/commit/2a300d5b03247e9dbb3d6cbb14f60354bd0e0ad0

Thanks @raghubetina @nflorentin
